// this file was generated by better-cmake
// fs v0.6.3

#define fs_NAME "fs"
#define fs_AUTHOR "fs"
#define fs_VERSION "0.6.3"
#define fs_VERSION_MAJOR 0
#define fs_VERSION_MINOR 6
#define fs_VERSION_PATCH 3
