// this file was generated by better-cmake
// fs v0.9.0

#define fs_NAME "fs"
#define fs_AUTHOR "DaemonTsun"
#define fs_VERSION "0.9.0"
#define fs_VERSION_MAJOR 0
#define fs_VERSION_MINOR 9
#define fs_VERSION_PATCH 0
